### ISSUE TITLE
[Stages appear to ignore explosions/non player destruction]

### ISSUE THREAD

**Issue by UnlimatedStone9** [JarHax/Ore-Stages#41]
I set a stage to hide TFC rock types as PrimalCore common stone, when the player mines the blocks after achieving the set stage, the mod functions as intended, however I noticed that when using TNT the blocks still drop common stone (the block they were hidden as)

mods.orestages.OreStages.addReplacement("generifyrocktypes", <tfc:raw/granite>, <primal:common_stone>);

**Comment by Darkhax** [comment]
TNT or other non-player things have no player or stage to associate with the action of breaking. This is the intended behaviour.
