### ISSUE TITLE
[Hiding blocks with multiple layers doesn't update Hwyla block name]

### ISSUE THREAD

**Issue by UnlimatedStone9** [JarHax/Ore-Stages#42]
As you can see I have copper ores.
![image](https://user-images.githubusercontent.com/40124890/65361508-b0250080-dbfb-11e9-9cc9-d618ec058730.png)
This copper ore is then hidden as common conglomerate stone, that works perfectly fine.
![image](https://user-images.githubusercontent.com/40124890/65361524-c468fd80-dbfb-11e9-81e9-a6a52bd06c46.png)
Now all conglomerate stone and any blocks that are hidden as conglomerate stone get hidden as common stone, however since this is the second time the copper ore block is getting hidden it keeps its conglomerate stone name, unlike actual conglomerate stone which is now displayed as common stone.
![image](https://user-images.githubusercontent.com/40124890/65361568-f4180580-dbfb-11e9-9219-ba356944eae0.png)

Multilayered hiding of block names for Hwyla would be a huge improvement.

**Comment by Darkhax** [comment]
Multi layering of blocks is not officially supported. This will be reviewed once the mod is ported to a version beyond 1.13.
