### ISSUE TITLE
[Suggestion] 1.16 Port

### ISSUE THREAD

**Issue by Jakobuo** [JarHax/Ore-Stages#45]
This is probably an annoying question to ask, but I didnt find the answer.

Will there be a 1.16(.4) port in predictable time?

**Comment by Fireztonez** [comment]
If you can port Ore-stages for Minecraft 1.16.5 +, I really want to use in the modpack I working on right now.

Continue your amazing work 😜

**Comment by Darkhax** [comment]
The mod will be ported eventually. GitHub is not an appropriate forum for asking about game version updates.
