### ISSUE TITLE
Luminous Blocks are still Luminous

### ISSUE THREAD

**Issue by mistaboom** [JarHax/Ore-Stages#47]
minecraft version 1.12.2

Steps to Replicate:
To replicate, simply hide glowstone behind some netherrack with any gamestage, then go to the nether. The "Netherrack" will be glowing with the same light level as the glowstone.

Why I hope you can fix this:
I was trying to implement a cool story bit where you free some npcs from a dimension and the dimension lights up with the granting of a gamestage with a quest completion. I've got the Glowstone generating in the dimension and it can be hidden and revealed by the gamestage and quest completion but the fake "stone" i have replaced it with glows like glowstone.

**Comment by Darkhax** [comment]
Unfortunately this is a limitation of the game engine and can not be reasonably fixed. With newer versions of the game there is a bit more wiggle room for faking light levels of blocks however there would be performance concerns.
